# Generated by Django 5.0.3 on 2024-03-15 17:57

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=20)),
                ('fecha_viaje', models.DateField()),
                ('actividades_realizadas', models.CharField(max_length=300)),
                ('descripcion', ckeditor.fields.RichTextField(null=True)),
                ('postal', models.ImageField(blank=True, null=True, upload_to='postales')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
